---
title: "Assignment 6"
author: "Sondre Løvås"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(rvest)
library(dplyr)
```

```{r countyList}
counties = list("Nordland", "TromsogFinnmark", "Trndelag", "MreogRomsdal", "Rogaland", 
                "Vestland", "Innlandet", "Oslo", "VestfoldogTelemark", "Viken", "Agder", "Utenlands")
```

```{r scrapeDate}
scrapeDate <- function(webpage, monthNum) {
  count <- 0
  df <- NULL
  currentCounty <- NULL
  
  table <- webpage %>% html_nodes(xpath = "//table") %>% html_nodes("table tr") %>% html_text()
  
  for (word in table) {
    word <- gsub("[^a-zA-Z]", "", word)  # Only keep the characters in the string.
    
    # If a county is found, set the current county and reset the counter.
    if (word %in% counties) {
      currentCounty <- word
      count <- 0
    }
    
    # check for key word and increment number of key words found.
    if (grepl("Konkurspning", word)) {  
      count <- count + 1
    }
    
    if (word == "") {  # If the word is an empty string, a new county follows.
      if (!is.null(currentCounty)) {  # Make sure that current county has gotten a value.
        if (is.null(df)){  # If the data frame is empty, create it.
          df <- data.frame(Month=monthNum, County=currentCounty, Count=count)
        } else {  # If the data frame is not empty, add to it.
          newEntry <- data.frame(Month=monthNum, County=currentCounty, Count=count)
          df <- rbind(df, newEntry)
        }
      }
    }
  }

  return(df)
}
```

```{r getLiquidadionData}
getLiquidationData <- function(year, fromMonth, toMonth) {
  df <- NULL
  
  while(fromMonth <= toMonth){
    daysInMonth <- days_in_month(fromMonth)  # Get the number of days in the month.
    currentMonth <- 0
    
    # The URL needs a date in the format dd.mm.yyyy 
    if (fromMonth < 10) {
      currentMonth <- sprintf("0%s", fromMonth)
    } else {
      currentMonth <- as.character(fromMonth)
    }
    
    url <- 
      sprintf("https://w2.brreg.no/kunngjoring/kombisok.jsp?datoFra=01.%s.%s&datoTil=%s.%s.%s&id_region=0&id_niva1=51&id_niva2=-+-+-&id_bran sje1=0",
              currentMonth, year, daysInMonth, currentMonth, year)  # Manipulate the URL go get the data from the current month.
    webpage <- read_html(url)
    str(webpage)
    
    if (is.null(df)) {  # If the data frame is empty, create it.
      df <- scrapeDate(webpage, currentMonth)
    } else {  # If the data frame is not empty, add to it.
      newEntry <- scrapeDate(webpage, currentMonth)
      df <- rbind(df, newEntry)
    }
    
    fromMonth <- as.numeric(fromMonth) + 1
  }
  
  return(df)
}
```

```{r createDataFrames, include=FALSE}
df2019 <- getLiquidationData(2019, 1, 12)  # Get the number of bankruptcies in 2019.
df2020 <- getLiquidationData(2020, 1, 9)  # Get the number of bankruptcies from January to September in 2020.
# Add cumulative sum attribute to data frames.
df2019$csum <- ave(df2019$Count, df2019$County, FUN = cumsum)
df2020$csum <- ave(df2020$Count, df2020$County, FUN = cumsum)
```
This report analyzes data from http://w2.brreg.no/kunngjoring/ to see if COVID-19 had an impact on the amount of bankruptcies in Norway.

```{r plotData, fig.width=11, fig.height=7, fig.cap="Monthly cumulative sum of bankruptcies in Norway by county.", fig.align="center"}
ggplot() + 
  geom_line(data=df2019, aes(x=Month, y=csum, color="2019", group=County), size=1.3) +
  geom_line(data=df2020, aes(x=Month, y=csum, color="2020", group=County), size=1.3) +
  labs(x="", y="", color="Year") +
  facet_wrap(~County)
```

The graph shows that we cannot yet conclude that the pandemic had an impact on bankruptcies in Norway.